export interface IdeaPayload {
  ideaText: string;
  targetType: 'coding_agent' | 'freelancer_brief' | 'hackathon_pitch' | 'no_code';
}

export interface Question {
  id: string;
  questionText: string;
  questionType: 'single_select' | 'multi_select' | 'free_text';
  options?: string[];
}

export interface Answer {
  questionId: string;
  value: string | string[];
}

// Mocking the LLM question generation
export const mockGenerateQuestions = async (_payload: IdeaPayload): Promise<Question[]> => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve([
        {
          id: 'q1',
          questionText: 'What is the primary goal or feature of this project?',
          questionType: 'free_text',
        },
        {
          id: 'q2',
          questionText: 'Which platform(s) are you targeting?',
          questionType: 'multi_select',
          options: ['Web', 'iOS', 'Android', 'Desktop'],
        },
        {
          id: 'q3',
          questionText: 'Do you need user authentication?',
          questionType: 'single_select',
          options: ['Yes', 'No', 'Not sure yet'],
        },
        {
          id: 'q4',
          questionText: 'Do you plan to monetize this, and if so, how?',
          questionType: 'free_text',
        }
      ]);
    }, 1500); // simulate LLM delay
  });
};

// Mocking the LLM prompt synthesis
export const mockSynthesizePrompt = async (
  idea: IdeaPayload,
  answers: Answer[],
  questions: Question[]
): Promise<string> => {
  return new Promise((resolve) => {
    setTimeout(() => {
      const answersText = answers.map(a => {
        const q = questions.find(q => q.id === a.questionId);
        return `**${q?.questionText}**\n${Array.isArray(a.value) ? a.value.join(', ') : a.value}`;
      }).join('\n\n');

      resolve(`# Project Brief: ${idea.ideaText}

## Target Audience
${idea.targetType}

## Core Requirements
${answersText}

## Recommended Architecture
- **Frontend**: React/Vite with Tailwind CSS
- **Backend**: Supabase (Postgres)
- **Deployment**: Vercel/Netlify

*This brief was generated by Bedrock.*
`);
    }, 2500);
  });
};
